platform :ios, '9.0'

target ‘kaiyan’ do
pod 'AFNetworking', '~> 3.0’
pod 'Toast', '~> 2.4'
pod 'FMDB', '~> 2.5'
pod 'Masonry', '~> 1.0.1'
pod 'SDAutoLayout','~>2.1.3'
pod 'YYModel','~>1.0.4'
pod 'LPActionSheet', '~> 1.0'
pod 'IQKeyboardManager'
pod 'SDCycleScrollView','~> 1.75'
end

